const loremIpsum =
    '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fringilla nulla enim. Nunc viverra suscipit lorem, sed lacinia odio commodo et. Aliquam iaculis mauris orci, quis dignissim ipsum faucibus non. Etiam id leo varius, finibus enim non, consequat ex. Proin in turpis imperdiet, condimentum lorem at, hendrerit sapien. Curabitur vitae turpis in orci cursus commodo. Integer mollis vulputate lobortis. Aliquam vitae elit elit. Mauris sit amet elementum risus, et posuere metus. Donec vehicula, turpis sed vulputate venenatis, quam neque elementum odio, sed euismod odio ex eget dui. Cras sit amet lacus tortor. Cras porttitor cursus mauris et tempus. Ut hendrerit enim et lobortis scelerisque.
    
Nunc id aliquet mauris. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In in magna sodales, tincidunt diam quis, aliquam sapien. Vestibulum vel sapien viverra nibh vehicula suscipit nec nec ligula. Aliquam erat volutpat. Nam eu ipsum luctus arcu ultrices luctus. Quisque lobortis pharetra sem quis feugiat. Sed tortor neque, laoreet ac arcu id, tempus auctor magna. Nulla facilisi. Vivamus elementum nisi at auctor rutrum.

Suspendisse vel libero sit amet nulla cursus fermentum non vel eros. Suspendisse elementum elementum odio nec consectetur. Nulla tempor tellus ac eros efficitur, eu eleifend est facilisis. Suspendisse nec malesuada mauris, sed laoreet urna. Vestibulum tincidunt ut velit eget efficitur. Fusce in varius velit. Cras nec orci felis. Praesent pellentesque nec est vel dapibus. Aliquam non est in lorem mattis dictum sed eget metus. Suspendisse eleifend est a ante facilisis laoreet. Etiam convallis nisi hendrerit felis fermentum imperdiet. In vitae quam sem. Maecenas suscipit ex lacinia fermentum sodales. Nullam sit amet felis nec neque scelerisque ornare. Suspendisse nec risus facilisis, scelerisque urna non, gravida est.

Vivamus libero neque, porta in ante vitae, viverra molestie tortor. Sed commodo tellus ut interdum finibus. Etiam a fringilla nibh. Morbi eget risus in lacus pretium pharetra et non sapien. Praesent ac augue id ex eleifend ultricies. Integer lacinia leo in justo ultrices, eget mattis arcu luctus. Vivamus placerat quam non ultrices rhoncus. Mauris blandit nisi sit amet mi mattis, sed ultrices magna fermentum. Ut fermentum orci et dictum fringilla. In arcu ante, cursus ac velit ut, pretium gravida nisl. In vel metus sit amet eros bibendum sollicitudin. Integer sed massa sed felis luctus bibendum. Phasellus risus tellus, finibus nec maximus non, rhoncus sit amet purus. Nulla facilisi. Aenean quis dolor at ante tristique eleifend.

Etiam eget elementum ex. Cras id felis at nisi blandit sagittis non ac massa. Nam a tellus in arcu faucibus sollicitudin tempus vitae elit. Integer purus ante, feugiat sed efficitur eu, rutrum tristique velit. Vestibulum viverra turpis ac euismod tempor. Fusce magna velit, volutpat rutrum ex eget, elementum vestibulum tellus. In varius mauris quis nibh eleifend porta. In accumsan eros tortor. Cras ipsum tellus, faucibus molestie facilisis a, malesuada eu sapien. Morbi ullamcorper ultrices vehicula.''';
