final List<Map<String, dynamic>> news = [
  {
    'source': 'CNN Indonesia',
    'time': '6 hours ago',
    'verifiedSource': true,
    'title': 'Alexander wears modified helmet in road races',
    'imageUrl': 'assets/6.jpg',
    'category': 'Sports',
  },
  {
    'source': 'BBC News',
    'time': '3 hours ago',
    'verifiedSource': true,
    'title': 'Scientists discover new species of bird in the Amazon',
    'imageUrl': 'assets/2.jpeg',
    'category': 'Science',
  },
  {
    'source': 'The Guardian',
    'time': '1 hour ago',
    'verifiedSource': true,
    'title': 'Government announces new measures to combat air pollution',
    'imageUrl': 'assets/1.jpg',
    'category': 'Health',
  },
  {
    'source': 'ESPN',
    'time': '2 hours ago',
    'verifiedSource': true,
    'title': 'LeBron James scores 50 points in Lakers win over Nets',
    'imageUrl': 'assets/5.jpg',
    'category': 'Sports',
  },
  {
    'source': 'TechCrunch',
    'time': '5 hours ago',
    'verifiedSource': true,
    'title': 'Google announces new AI-powered chatbot for customer service',
    'imageUrl': 'assets/4.jpeg',
    'category': 'Tech',
  },
  {
    'source': 'BBC Sport',
    'time': '3 hours ago',
    'verifiedSource': true,
    'title': 'Tiger Woods makes successful return to golf after injury',
    'imageUrl': 'assets/3.jpg',
    'category': 'Sports',
  },
];

final List<Map<String, dynamic>> recommended = [
  {
    'writerPic': 'assets/man1.jpeg',
    'source': 'John Smith',
    'time': 'March 25, 2023',
    'verifiedSource': true,
    'title': 'The Importance of Plyometric Training for Volleyball Players',
    'imageUrl': 'assets/7.jpg',
    'category': 'Sports',
  },
  {
    'writerPic': 'assets/man2.jpg',
    'source': 'Jane Williams',
    'time': 'March 24, 2023',
    'verifiedSource': true,
    'title': 'How a Plant-Based Diet Can Benefit Athletes',
    'imageUrl': 'assets/8.jpg',
    'category': 'Health',
  },
  {
    'writerPic': 'assets/man3.jpg',
    'source': 'Mark Davis',
    'time': 'March 23, 2023',
    'verifiedSource': true,
    'title': 'How to Invest Your Money for Long-Term Financial Stability',
    'imageUrl': 'assets/9.jpg',
    'category': 'Finances',
  },
  {
    'writerPic': 'assets/man1.jpeg',
    'source': 'Emily Chen',
    'time': 'March 22, 2023',
    'verifiedSource': true,
    'title': '5 Strategies for Successfully Navigating a Career Change',
    'imageUrl': 'assets/10.jpg',
    'category': 'Work',
  },
  {
    'writerPic': 'assets/man2.jpg',
    'source': 'David Rodriguez',
    'time': 'March 21, 2023',
    'verifiedSource': true,
    'title':
        'How to Protect Yourself from Cyber Threats in the Age of Remote Work',
    'imageUrl': 'assets/11.jpg',
    'category': 'Tech',
  },
];
